name: "[Icon] Add icon from issue"
on:
  issues:
    types: [labeled]

jobs:
  add-icon:
    runs-on: ubuntu-latest
    # This condition ensures the job only runs when the specified label is added
    if: contains(github.event.pull_request.labels.*.name, 'approved')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run parse-icon-form.js
        run: node parse-icon-form.js
        env:
          INPUT_ISSUE_BODY: ${{ github.event.issue.body }}
          INPUT_ISSUE_AUTHOR_ID: ${{ github.event.issue.user.id }}
          INPUT_ISSUE_AUTHOR_LOGIN: ${{ github.event.issue.user.login }}
